#!/usr/bin/env python3
"""CI drift guard for the golden fixtures (#5, checklist 5e).

Runs every generator under tools/golden/ into a temp dir (via its out-dir
argument), then byte-compares each produced file with the committed copy under
game/tests/golden/. Fails (exit 1) on:
  - DIFFERS : generator output differs from the committed file
  - MISSING : a generator produces a file that is not committed
  - ORPHAN  : a committed fixture (*.json) that no generator produces
  - CONFLICT: two generators produce the same fixture path
  - GENFAIL : a generator exited non-zero
  - UNLISTED: a tools/golden/gen_*.py not registered in GENERATORS below

Usage: python tools/golden/check_drift.py
Nothing under game/tests/golden is ever written.
"""
import difflib
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
GOLDEN_ROOT = os.path.join(ROOT, 'game', 'tests', 'golden')

# (generator script, fixture subdir of game/tests/golden it writes into).
GENERATORS = [
    ('gen_orderbook.py', 'orderbook'),
    ('gen_settlement.py', 'settlement'),
    ('gen_draws.py', 'draws'),
    ('gen_sample_draws.py', 'draws'),
    ('gen_transit_hazards.py', 'transit_hazards'),
    ('gen_clearing.py', 'clearing'),
]
FIXTURE_EXT = '.json'


def _list_fixtures(base):
    found = {}
    for dirpath, _dirs, files in os.walk(base):
        for name in files:
            if name.endswith(FIXTURE_EXT):
                full = os.path.join(dirpath, name)
                found[os.path.relpath(full, base).replace(os.sep, '/')] = full
    return found


def _read(path):
    with open(path, 'rb') as f:
        return f.read()


def _diff_summary(rel, committed, produced, limit=12):
    a = committed.decode('utf-8', 'replace').splitlines()
    b = produced.decode('utf-8', 'replace').splitlines()
    lines = list(difflib.unified_diff(a, b, 'committed/' + rel, 'regenerated/' + rel, lineterm='', n=0))
    out = lines[:limit]
    if len(lines) > limit:
        out.append('... (%d more diff lines)' % (len(lines) - limit))
    return ['    ' + line for line in out]


def run_generators(tmp):
    """Run each generator into tmp/<n>/<subdir>; return ({rel: (path, script)}, problems)."""
    produced, problems = {}, []
    listed = {g for g, _ in GENERATORS}
    for name in sorted(os.listdir(HERE)):
        if name.startswith('gen_') and name.endswith('.py') and name not in listed:
            problems.append('UNLISTED: tools/golden/%s is not registered in check_drift.GENERATORS' % name)
    for n, (script, subdir) in enumerate(GENERATORS):
        base = os.path.join(tmp, str(n))
        out_dir = os.path.join(base, subdir)
        os.makedirs(out_dir)
        proc = subprocess.run([sys.executable, os.path.join(HERE, script), out_dir],
                              cwd=ROOT, capture_output=True, text=True)
        if proc.returncode != 0:
            tail = '\n'.join('    ' + line for line in proc.stderr.strip().splitlines()[-10:])
            problems.append('GENFAIL: %s exited %d\n%s' % (script, proc.returncode, tail))
            continue
        for rel, full in _list_fixtures(base).items():
            if rel in produced:
                problems.append('CONFLICT: %s is produced by more than one generator (%s)' % (rel, script))
            else:
                produced[rel] = (full, script)
    return produced, problems


def check(golden_root=GOLDEN_ROOT):
    """Return a list of problem strings (empty means no drift)."""
    committed = _list_fixtures(golden_root)
    with tempfile.TemporaryDirectory() as tmp:
        produced, problems = run_generators(tmp)
        for rel in sorted(produced):
            full, script = produced[rel]
            if rel not in committed:
                problems.append('MISSING: %s is produced by %s but not committed' % (rel, script))
                continue
            got, want = _read(full), _read(committed[rel])
            if got != want:
                problems.append('DIFFERS: %s (regenerated by %s, %d vs %d bytes)\n%s' % (
                    rel, script, len(got), len(want), '\n'.join(_diff_summary(rel, want, got))))
        for rel in sorted(set(committed) - set(produced)):
            problems.append('ORPHAN: %s is committed but no generator produces it' % rel)
    return problems


def main(argv=None, golden_root=GOLDEN_ROOT):
    problems = check(golden_root)
    if problems:
        print('Golden fixture drift detected (%d problem(s)):' % len(problems))
        for p in problems:
            print('  ' + p)
        print('Regenerate with the generator named above and commit the result.')
        return 1
    print('Golden fixtures match: %d generators, no drift.' % len(GENERATORS))
    return 0


if __name__ == '__main__':
    sys.exit(main())
