extends RefCounted
## ReplayDrawSource tests against the shared fixture golden/draws/sample.json
## (generated by tools/golden/gen_sample_draws.py). A test returns "ok" to pass.

const FIXTURE := "res://tests/golden/draws/sample.json"

func _entries() -> Array:
	var parsed = JSON.parse_string(FileAccess.get_file_as_string(FIXTURE))
	return parsed if parsed is Array else []

## Replays the full fixture in order; returns the source and the shuffled array.
func _replay_all(src: ReplayDrawSource) -> Dictionary:
	var out := {}
	out["randint"] = src.randint(1, 6)
	out["random"] = src.random()
	out["uniform"] = src.uniform(0.5, 2.5)
	out["choice"] = src.choice(["mars", "ceres", "vesta"])
	out["randrange"] = src.randrange(0, 20, 5)
	out["gauss"] = src.gauss(0.0, 1.0)
	var arr := [10, 20, 30, 40, 50]
	src.shuffle(arr)
	out["shuffle"] = arr
	out["randint2"] = src.randint(1, 100)
	return out

func test_fixture_loads() -> String:
	var e := _entries()
	if e.size() != 8:
		return "expected 8 fixture entries, got %d" % e.size()
	return "ok"

func test_replay_in_order_succeeds() -> String:
	var e := _entries()
	var src := ReplayDrawSource.new(e)
	var got := _replay_all(src)
	src.assert_exhausted()
	if not src.ok():
		return "unexpected failure: %s" % [src.failure]
	if got["randint"] != int(e[0]["result"]): return "randint value"
	if got["random"] != float(e[1]["result"]): return "random value"
	if got["uniform"] != float(e[2]["result"]): return "uniform value"
	if got["choice"] != e[3]["result"]: return "choice value"
	if got["randrange"] != int(e[4]["result"]): return "randrange value"
	if got["gauss"] != float(e[5]["result"]): return "gauss value"
	if got["randint2"] != int(e[7]["result"]): return "second randint value"
	var perm: Array = e[6]["result"]
	var orig := [10, 20, 30, 40, 50]
	for i in perm.size():
		if got["shuffle"][i] != orig[int(perm[i])]:
			return "shuffle permutation not applied at %d" % i
	return "ok"

func test_wrong_method_fails_at_index() -> String:
	var src := ReplayDrawSource.new(_entries())
	src.randint(1, 6)
	src.random()
	src.random()  # entry 2 is uniform
	if src.ok():
		return "expected failure"
	if src.failure["index"] != 2 or src.failure["reason"] != "mismatch":
		return "wrong failure: %s" % [src.failure]
	if src.failure["expected"]["call"] != "uniform" or src.failure["actual"]["call"] != "random":
		return "expected/actual wrong: %s" % [src.failure]
	return "ok"

func test_wrong_args_fails() -> String:
	var src := ReplayDrawSource.new(_entries())
	src.randint(1, 7)  # recorded randint(1, 6)
	if src.ok():
		return "expected failure"
	if src.failure["index"] != 0 or src.failure["reason"] != "mismatch":
		return "wrong failure: %s" % [src.failure]
	return "ok"

func test_failure_is_sticky_and_does_not_crash() -> String:
	var src := ReplayDrawSource.new(_entries())
	src.randint(9, 9)
	var first: Dictionary = src.failure.duplicate(true)
	src.randint(1, 6)  # would have matched entry 0; matching has stopped
	src.assert_exhausted()
	if src.failure != first:
		return "failure was overwritten: %s" % [src.failure]
	return "ok"

func test_extra_draw_fails() -> String:
	var src := ReplayDrawSource.new(_entries())
	_replay_all(src)
	if not src.ok():
		return "replay should have succeeded: %s" % [src.failure]
	src.random()
	if src.ok():
		return "expected failure on extra draw"
	if src.failure["index"] != 8 or src.failure["reason"] != "extra_draw":
		return "wrong failure: %s" % [src.failure]
	return "ok"

func test_missing_draw_fails_on_assert_exhausted() -> String:
	var src := ReplayDrawSource.new(_entries())
	src.randint(1, 6)
	src.random()
	if not src.ok():
		return "premature failure: %s" % [src.failure]
	src.assert_exhausted()
	if src.ok():
		return "expected missing_draw failure"
	if src.failure["index"] != 2 or src.failure["reason"] != "missing_draw":
		return "wrong failure: %s" % [src.failure]
	return "ok"

func test_native_source_is_seeded() -> String:
	var a := NativeDrawSource.new(42)
	var b := NativeDrawSource.new(42)
	for i in 20:
		if a.randint(1, 6) != b.randint(1, 6): return "randint diverged"
		if a.randrange(0, 20, 5) != b.randrange(0, 20, 5): return "randrange diverged"
	var v := a.randint(1, 6)
	if v < 1 or v > 6: return "randint out of range"
	var arr := [1, 2, 3, 4]
	a.shuffle(arr)
	arr.sort()
	if arr != [1, 2, 3, 4]: return "shuffle lost elements"
	return "ok"
